import {
  Ban,
  CircleUserRound,
  History,
  KeyRound,
  KeySquare,
  LifeBuoy,
  LogIn,
  LogOut,
  MailPlus,
  MonitorX,
  PartyPopper,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  UserCheck,
  UserCog,
  UserMinus,
  UserX,
} from '@lucide/vue'

import type { ActivityEntry } from '@/api/account'
import { describeActivity } from '@/auth/activity'
import { makeActivity } from '@/test/fixtures'

function entry(
  event: string,
  details: Record<string, unknown> = {},
  changes: Partial<ActivityEntry> = {},
) {
  return makeActivity({ event, details, user_name: 'Sam Lee', ...changes })
}

const admin = { actor_name: 'Alex Morgan' }

// [event, details, extra fields, your own log, the household log, tone, icon]
const cases: [
  string,
  Record<string, unknown>,
  Partial<ActivityEntry>,
  string,
  string,
  string,
  unknown,
][] = [
  ['setup_completed', {}, {}, 'Set up Cashcove', 'Sam Lee set up Cashcove', 'success', PartyPopper],
  [
    'signed_in',
    { method: 'passkey' },
    {},
    'Signed in with a passkey',
    'Sam Lee signed in with a passkey',
    'success',
    LogIn,
  ],
  [
    'signed_in',
    { method: 'totp' },
    {},
    'Signed in with an authenticator code',
    'Sam Lee signed in with an authenticator code',
    'success',
    LogIn,
  ],
  ['signed_in', { method: 'mystery' }, {}, 'Signed in', 'Sam Lee signed in', 'success', LogIn],
  [
    'sign_in_failed',
    { method: 'password' },
    {},
    'Failed sign-in with a password',
    'Failed sign-in with a password for Sam Lee',
    'error',
    ShieldAlert,
  ],
  [
    'sign_in_failed',
    {},
    { user_name: null },
    'Failed sign-in',
    'Failed sign-in for an unknown email',
    'error',
    ShieldAlert,
  ],
  [
    'verification_failed',
    { method: 'recovery_code' },
    {},
    "Couldn't confirm it was you with a recovery code",
    "Sam Lee couldn't confirm it was them with a recovery code",
    'warning',
    ShieldAlert,
  ],
  ['signed_out', {}, {}, 'Signed out', 'Sam Lee signed out', 'neutral', LogOut],
  [
    'session_revoked',
    { count: 1 },
    {},
    'Signed out 1 other device',
    'Sam Lee signed out 1 other device',
    'neutral',
    MonitorX,
  ],
  [
    'session_revoked',
    { count: 3 },
    {},
    'Signed out 3 other devices',
    'Sam Lee signed out 3 other devices',
    'neutral',
    MonitorX,
  ],
  [
    'session_revoked',
    { device: 'Safari on iPhone' },
    {},
    'Signed out Safari on iPhone',
    'Sam Lee signed out Safari on iPhone',
    'neutral',
    MonitorX,
  ],
  [
    'session_revoked',
    {},
    {},
    'Signed out a device',
    'Sam Lee signed out a device',
    'neutral',
    MonitorX,
  ],
  [
    'password_changed',
    {},
    {},
    'Changed your password',
    'Sam Lee changed their password',
    'info',
    KeyRound,
  ],
  [
    'profile_updated',
    { changed: ['name'] },
    {},
    'Changed your name',
    'Sam Lee changed their name',
    'info',
    CircleUserRound,
  ],
  [
    'profile_updated',
    { changed: ['email'] },
    {},
    'Changed your email',
    'Sam Lee changed their email',
    'info',
    CircleUserRound,
  ],
  [
    'profile_updated',
    { changed: ['name', 'email'] },
    {},
    'Changed your name and email',
    'Sam Lee changed their name and email',
    'info',
    CircleUserRound,
  ],
  [
    'profile_updated',
    {},
    {},
    'Changed your name',
    'Sam Lee changed their name',
    'info',
    CircleUserRound,
  ],
  [
    'two_factor_enabled',
    {},
    {},
    'Turned on two-step verification',
    'Sam Lee turned on two-step verification',
    'success',
    ShieldCheck,
  ],
  [
    'two_factor_disabled',
    {},
    {},
    'Turned off two-step verification',
    'Sam Lee turned off two-step verification',
    'warning',
    ShieldOff,
  ],
  [
    'two_factor_reset',
    {},
    admin,
    'Alex Morgan turned off your two-step verification',
    "Alex Morgan turned off Sam Lee's two-step verification",
    'warning',
    ShieldOff,
  ],
  [
    'two_factor_reset',
    {},
    {},
    'An admin turned off your two-step verification',
    "An admin turned off Sam Lee's two-step verification",
    'warning',
    ShieldOff,
  ],
  [
    'two_factor_reset',
    { via: 'command line' },
    {},
    'Two-step verification was turned off for you on the server',
    'Two-step verification was turned off for Sam Lee on the server',
    'warning',
    ShieldOff,
  ],
  [
    'recovery_codes_created',
    {},
    {},
    'Created new recovery codes',
    'Sam Lee created new recovery codes',
    'info',
    LifeBuoy,
  ],
  [
    'recovery_code_used',
    { codes_left: 7 },
    {},
    'Signed in with a recovery code (7 left)',
    'Sam Lee signed in with a recovery code (7 left)',
    'warning',
    LifeBuoy,
  ],
  [
    'recovery_code_used',
    {},
    {},
    'Signed in with a recovery code',
    'Sam Lee signed in with a recovery code',
    'warning',
    LifeBuoy,
  ],
  [
    'passkey_added',
    { name: 'iCloud Keychain' },
    {},
    'Added a passkey · iCloud Keychain',
    'Sam Lee added a passkey · iCloud Keychain',
    'success',
    KeySquare,
  ],
  ['passkey_added', {}, {}, 'Added a passkey', 'Sam Lee added a passkey', 'success', KeySquare],
  [
    'passkey_removed',
    { name: 'Old phone' },
    {},
    'Removed a passkey · Old phone',
    'Sam Lee removed a passkey · Old phone',
    'neutral',
    KeySquare,
  ],
  [
    'user_invited',
    { email: 'riley@example.com', role: 'viewer' },
    { user_name: 'Alex Morgan' },
    'Alex Morgan invited riley@example.com as a viewer',
    'Alex Morgan invited riley@example.com as a viewer',
    'info',
    MailPlus,
  ],
  [
    'user_invited',
    { email: 'riley@example.com', role: 'admin', renewed: true },
    { ...admin, user_name: null },
    'Alex Morgan sent a new invitation link to riley@example.com as an admin',
    'Alex Morgan sent a new invitation link to riley@example.com as an admin',
    'info',
    MailPlus,
  ],
  [
    'user_invited',
    { email: 'riley@example.com', role: 'owner' },
    { user_name: null },
    'Someone invited riley@example.com',
    'Someone invited riley@example.com',
    'info',
    MailPlus,
  ],
  [
    'invitation_revoked',
    { email: 'riley@example.com' },
    admin,
    'Alex Morgan cancelled the invitation for riley@example.com',
    'Alex Morgan cancelled the invitation for riley@example.com',
    'neutral',
    Ban,
  ],
  [
    'invitation_revoked',
    { email: 'riley@example.com' },
    {},
    'Sam Lee cancelled the invitation for riley@example.com',
    'Sam Lee cancelled the invitation for riley@example.com',
    'neutral',
    Ban,
  ],
  [
    'invitation_accepted',
    {},
    {},
    'Joined the household',
    'Sam Lee joined the household',
    'success',
    UserCheck,
  ],
  [
    'user_updated',
    { role: 'admin' },
    admin,
    'Alex Morgan made you an admin',
    'Alex Morgan made Sam Lee an admin',
    'info',
    UserCog,
  ],
  [
    'user_updated',
    { is_active: false },
    admin,
    'Alex Morgan turned off your account',
    "Alex Morgan turned off Sam Lee's account",
    'warning',
    UserX,
  ],
  [
    'user_updated',
    { role: 'viewer', is_active: true },
    {},
    'An admin made you a viewer and turned your account back on',
    "An admin made Sam Lee a viewer and turned Sam Lee's account back on",
    'info',
    UserCog,
  ],
  [
    'user_updated',
    {},
    admin,
    'Alex Morgan updated your account',
    "Alex Morgan updated Sam Lee's account",
    'info',
    UserCog,
  ],
  [
    'user_removed',
    { name: 'Riley Chen' },
    admin,
    'Alex Morgan removed Riley Chen',
    'Alex Morgan removed Riley Chen',
    'warning',
    UserMinus,
  ],
  [
    'user_removed',
    { email: 'riley@example.com' },
    {},
    'Sam Lee removed riley@example.com',
    'Sam Lee removed riley@example.com',
    'warning',
    UserMinus,
  ],
  [
    'user_removed',
    {},
    {},
    'Sam Lee removed someone',
    'Sam Lee removed someone',
    'warning',
    UserMinus,
  ],
  [
    'password_reset_created',
    {},
    admin,
    'Alex Morgan created a password reset link for you',
    'Alex Morgan created a password reset link for Sam Lee',
    'info',
    KeyRound,
  ],
  [
    'password_reset_created',
    {},
    {},
    'An admin created a password reset link for you',
    'An admin created a password reset link for Sam Lee',
    'info',
    KeyRound,
  ],
  [
    'password_reset_created',
    { via: 'command line' },
    {},
    'A password reset link was created for you on the server',
    'A password reset link was created for Sam Lee on the server',
    'info',
    KeyRound,
  ],
  [
    'password_reset',
    {},
    {},
    'Chose a new password with a reset link',
    'Sam Lee chose a new password with a reset link',
    'info',
    KeyRound,
  ],
  ['something_new', {}, {}, 'something new', 'something new', 'neutral', History],
]

describe('describeActivity', () => {
  it.each(cases)('%s %j', (event, details, changes, mine, household, tone, icon) => {
    const item = entry(event, details, changes)
    expect(describeActivity(item)).toEqual({ title: mine, tone, icon })
    expect(describeActivity(item, 'household')).toEqual({ title: household, tone, icon })
  })

  it('does not name an admin who changed their own account', () => {
    const item = entry(
      'user_updated',
      { role: 'viewer' },
      { user_name: 'Alex Morgan', actor_name: 'Alex Morgan' },
    )
    expect(describeActivity(item).title).toBe('An admin made you a viewer')
  })

  it('calls an unknown person someone', () => {
    const item = entry('signed_out', {}, { user_name: null })
    expect(describeActivity(item, 'household').title).toBe('Someone signed out')
  })
})
