import {
  ArrowBigUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronUp,
  Circle,
  CircleCheck,
  CircleCheckBig,
  CircleSmall,
  CircleX,
  CloudUpload,
  Command,
  CornerDownLeft,
  Delete,
  Info,
  Maximize,
  Menu,
  Minimize,
  Minus,
  Option,
  Palette,
  Paperclip,
  Pause,
  Pencil,
  Pipette,
  Play,
  Plus,
  RefreshCw,
  Search,
  Space,
  Square,
  SquareCheck,
  SquareMinus,
  Star,
  StarHalf,
  TriangleAlert,
  UnfoldVertical,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  X,
} from '@lucide/vue'
import type { IconAliases, IconSet } from 'vuetify'
import { VComponentIcon } from 'vuetify/components/VIcon'

// Vuetify's internal icons (checkboxes, pagination, selects...) rendered with Lucide components,
// so the whole app shares one actively maintained icon family.
export const aliases: IconAliases = {
  collapse: ChevronUp,
  complete: Check,
  cancel: CircleX,
  close: X,
  delete: CircleX,
  clear: CircleX,
  success: CircleCheckBig,
  info: Info,
  warning: TriangleAlert,
  error: CircleX,
  prev: ChevronLeft,
  next: ChevronRight,
  checkboxOn: SquareCheck,
  checkboxOff: Square,
  checkboxIndeterminate: SquareMinus,
  delimiter: CircleSmall,
  sortAsc: ArrowUp,
  sortDesc: ArrowDown,
  expand: ChevronDown,
  menu: Menu,
  subgroup: ChevronDown,
  dropdown: ChevronDown,
  radioOn: CircleCheck,
  radioOff: Circle,
  edit: Pencil,
  ratingEmpty: Star,
  ratingFull: Star,
  ratingHalf: StarHalf,
  loading: RefreshCw,
  first: ChevronsLeft,
  last: ChevronsRight,
  unfold: UnfoldVertical,
  file: Paperclip,
  plus: Plus,
  minus: Minus,
  calendar: Calendar,
  treeviewCollapse: ChevronDown,
  treeviewExpand: ChevronRight,
  tableGroupExpand: ChevronRight,
  tableGroupCollapse: ChevronDown,
  eyeDropper: Pipette,
  upload: CloudUpload,
  color: Palette,
  command: Command,
  ctrl: ChevronUp,
  space: Space,
  shift: ArrowBigUp,
  alt: Option,
  enter: CornerDownLeft,
  arrowup: ArrowUp,
  arrowdown: ArrowDown,
  arrowleft: ArrowLeft,
  arrowright: ArrowRight,
  backspace: Delete,
  play: Play,
  pause: Pause,
  fullscreen: Maximize,
  fullscreenExit: Minimize,
  volumeHigh: Volume2,
  volumeMedium: Volume1,
  volumeLow: Volume,
  volumeOff: VolumeX,
  search: Search,
}

export const lucide: IconSet = { component: VComponentIcon }
